# Server settings
server:
  port:8080
  address:localhost

# DATASOURCE
jdbc:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.2:3306/mysql?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456

# SPRING PROFILES
spring:
  #profiles:dev

# HTTP ENCODING
http:
  encoding.charset: UTF-8
  encoding.enable: true
  encoding.force: true

# MyBatis
#mybatis:
#  typeAliasesPackage: com.modou.**.domain
#  mapperLocations: classpath:/com/modou/**/mapper/*.xml
#  configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
  level:
     com.ibatis:DEBUG